apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2020-03-26T13:57:01Z"
  generation: 8
  name: worker
  namespace: default
  resourceVersion: "1135107"
  selfLink: /apis/apps/v1/namespaces/default/deployments/worker
  uid: 5b2bc297-83e2-4a20-9b77-101de3d84169
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: worker
    spec:
      automountServiceAccountToken: false
      containers:
      - args:
        - worker
        - --queue celery,uploads
        - --concurrency 1
        env:
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        image: codecov/enterprise:v4.4.12
        imagePullPolicy: Always
        name: workers
        resources:
          limits:
            cpu: 512m
            memory: 2048M
          requests:
            cpu: 256m
            memory: 2048M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          mountPropagation: None
          name: codecov-yml
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30
      volumes:
      - name: codecov-yml
        secret:
          defaultMode: 420
          optional: false
          secretName: codecov-yml
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-03-26T13:57:01Z"
    lastUpdateTime: "2020-03-27T12:54:30Z"
    message: ReplicaSet "worker-6c85b8f5c7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-03-31T13:12:34Z"
    lastUpdateTime: "2020-03-31T13:12:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 8
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
